import { Router } from "express";
import { ActivityLogRoutes } from "../module/activityLog/activityLog.route";
import { AdminRoutes } from "../module/admin/admin.route";
import { AuthRoutes } from "../module/auth/auth.route";
import { BuildingRoutes } from "../module/building/building.route";
import { ComplaintRoutes } from "../module/complaint/complaint.route";
import { DashboardRoutes } from "../module/dashboard/dashboard.route";
import { DocumentRoutes } from "../module/document/document.route";
import { ExpenseRoutes } from "../module/expense/expense.route";
import { FloorRoutes } from "../module/floor/floor.route";
import { InvoiceRoutes } from "../module/invoice/invoice.route";
import { LeaseRoutes } from "../module/lease/lease.route";
import { NotificationRoutes } from "../module/notification/notification.route";
import { OrganizationRoutes } from "../module/organization/organization.route";
import { PaymentRoutes } from "../module/payment/payment.route";
import { PlanConfigRoutes } from "../module/planConfig/planConfig.route";
import { RentAgreementRoutes } from "../module/rentAgreement/rentAgreement.route";
import { RentIncreaseRoutes } from "../module/rentIncrease/rentIncrease.route";
import { ReportsRoutes } from "../module/reports/reports.route";
import { SubscriptionRoutes } from "../module/subscription/subscription.route";
import { TenantRoutes } from "../module/tenant/tenant.route";
import { UnitRoutes } from "../module/unit/unit.route";
import { UserRoutes } from "../module/user/user.route";

const router = Router();

router.use("/auth", AuthRoutes);
router.use("/users", UserRoutes);
router.use("/admins", AdminRoutes);
router.use("/organizations", OrganizationRoutes);
router.use("/subscriptions", SubscriptionRoutes);
router.use("/plan-configs", PlanConfigRoutes);
router.use("/buildings", BuildingRoutes);
router.use("/floors", FloorRoutes);
router.use("/units", UnitRoutes);
router.use("/tenants", TenantRoutes);
router.use("/leases", LeaseRoutes);
router.use("/invoices", InvoiceRoutes);
router.use("/payments", PaymentRoutes);
router.use("/expenses", ExpenseRoutes);
router.use("/complaints", ComplaintRoutes);
router.use("/documents", DocumentRoutes);
router.use("/rent-agreements", RentAgreementRoutes);
router.use("/rent-increases", RentIncreaseRoutes);
router.use("/dashboard", DashboardRoutes);
router.use("/reports", ReportsRoutes);
router.use("/notifications", NotificationRoutes);
router.use("/activity-logs", ActivityLogRoutes);

export const IndexRoutes = router;
